name: firebase_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.8
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

